apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp2
spec:
  destination:
    namespace: myapp2
    server: https://kubernetes.default.svc
  source:
    path: dev
    repoURL: https://github.com/ArhNex/ArgoCD_test.git
    targetRevision: HEAD
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
      enabled: false 
    syncOptions:
      - CreateNamespace=true

